<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>AbpBookStore</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Volo.Abp.Ddd.Domain" Version="10.6.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AbpBookStore.Domain.Shared\AbpBookStore.Domain.Shared.csproj" />
  </ItemGroup>

</Project>
