using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Kdbndp;
using System.Data.Common;

namespace Kingbase.EntityFrameworkCore.Tests.Integration;

[Collection("Kingbase integration")]
public sealed class KingbaseCrudIntegrationTests
{
    private const string ConnectionVariable = "KINGBASE_TEST_CONNECTION";

    [Fact]
    public async Task Crud_roundtrip_against_real_kingbase()
    {
        var connectionString = Environment.GetEnvironmentVariable(ConnectionVariable);
        if (string.IsNullOrWhiteSpace(connectionString))
        {
            return;
        }

        await using var connection = await OpenConnectionAsync(connectionString);
        await ResetTableAsync(connection);

        var options = new DbContextOptionsBuilder<ProbeDbContext>()
            .UseKdbndp(connection, kingbaseOptionsAction: options => options.SetOracleCompatibilityMode())
            .Options;

        await using (var context = new ProbeDbContext(options))
        {
            context.Entities.Add(new ProbeEntity { Id = 1, Name = "alpha", Version = 1 });
            Assert.Equal(1, await context.SaveChangesAsync());
        }

        await using (var context = new ProbeDbContext(options))
        {
            var entity = await context.Entities.SingleAsync(row => row.Id == 1);
            Assert.Equal("alpha", entity.Name);

            entity.Name = "beta";
            entity.Version++;
            Assert.Equal(1, await context.SaveChangesAsync());
        }

        await using (var context = new ProbeDbContext(options))
        {
            var names = await context.Entities
                .Where(row => row.Id > 0)
                .OrderBy(row => row.Name)
                .Take(5)
                .Select(row => row.Name)
                .ToListAsync();

            Assert.Equal(["beta"], names);
            Assert.Equal(1, await context.Entities.Where(row => row.Id == 1).ExecuteDeleteAsync());
            Assert.False(await context.Entities.AnyAsync());
        }
    }

    [Fact]
    public async Task Insert_reads_database_generated_identity()
    {
        var connectionString = Environment.GetEnvironmentVariable(ConnectionVariable);
        if (string.IsNullOrWhiteSpace(connectionString))
        {
            return;
        }

        await using var connection = await OpenConnectionAsync(connectionString);

        await using (var command = connection.CreateCommand())
        {
            command.CommandText =
                """
                DROP TABLE IF EXISTS "efcore_identity_probe";
                CREATE TABLE "efcore_identity_probe" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "Name" text NOT NULL
                );
                """;
            await command.ExecuteNonQueryAsync();
        }

        var options = new DbContextOptionsBuilder<ProbeDbContext>()
            .UseKdbndp(connection, kingbaseOptionsAction: options => options.SetOracleCompatibilityMode())
            .Options;

        await using var context = new ProbeDbContext(options);
        var entity = new IdentityProbeEntity { Name = "generated" };
        context.IdentityEntities.Add(entity);

        Assert.Equal(1, await context.SaveChangesAsync());
        Assert.True(entity.Id > 0);
    }

    [Fact]
    public async Task EnsureCreated_creates_tables_from_the_ef_model()
    {
        var connectionString = Environment.GetEnvironmentVariable(ConnectionVariable);
        if (string.IsNullOrWhiteSpace(connectionString))
        {
            return;
        }

        var builder = new DbConnectionStringBuilder { ConnectionString = connectionString };
        builder["Database"] = "efcore_ensure_created_model_probe";

        var options = new DbContextOptionsBuilder<EnsureCreatedDbContext>()
            .UseKdbndp(builder.ConnectionString, kingbaseOptionsAction: options => options
                .SetOracleCompatibilityMode()
                .UseAdminDatabase("template1"))
            .Options;

        await using (var cleanup = new EnsureCreatedDbContext(options))
        {
            await cleanup.Database.EnsureDeletedAsync();
        }

        await using (var context = new EnsureCreatedDbContext(options))
        {
            Assert.True(await context.Database.EnsureCreatedAsync());
            context.Entities.Add(new EnsureCreatedEntity { Id = 1, Name = "created-by-ef" });
            Assert.Equal(1, await context.SaveChangesAsync());
            Assert.Equal("created-by-ef", await context.Entities.Select(row => row.Name).SingleAsync());
            Assert.True(await context.Database.EnsureDeletedAsync());
        }
    }

    [Fact]
    public async Task EnsureCreated_and_EnsureDeleted_manage_the_database()
    {
        var connectionString = Environment.GetEnvironmentVariable(ConnectionVariable);
        if (string.IsNullOrWhiteSpace(connectionString))
        {
            return;
        }

        var builder = new DbConnectionStringBuilder { ConnectionString = connectionString };
        builder["Database"] = "efcore_provider_lifecycle_probe";

        var options = new DbContextOptionsBuilder<EnsureCreatedDbContext>()
            .UseKdbndp(builder.ConnectionString, kingbaseOptionsAction: options => options
                .SetOracleCompatibilityMode()
                .UseAdminDatabase("template1"))
            .Options;

        await using (var cleanup = new EnsureCreatedDbContext(options))
        {
            await cleanup.Database.EnsureDeletedAsync();
        }

        await using (var context = new EnsureCreatedDbContext(options))
        {
            Assert.True(await context.Database.EnsureCreatedAsync());
            context.Entities.Add(new EnsureCreatedEntity { Id = 1, Name = "database-lifecycle" });
            Assert.Equal(1, await context.SaveChangesAsync());
        }

        await using (var context = new EnsureCreatedDbContext(options))
        {
            Assert.Equal("database-lifecycle", await context.Entities.Select(row => row.Name).SingleAsync());
            Assert.True(await context.Database.EnsureDeletedAsync());
            Assert.False(await context.Database.CanConnectAsync());
        }
    }

    [Fact]
    public async Task Explicit_sync_and_async_transactions_commit_and_rollback()
    {
        var connectionString = Environment.GetEnvironmentVariable(ConnectionVariable);
        if (string.IsNullOrWhiteSpace(connectionString))
        {
            return;
        }

        await using var connection = await OpenConnectionAsync(connectionString);
        await ResetTableAsync(connection);
        var options = new DbContextOptionsBuilder<ProbeDbContext>()
            .UseKdbndp(connection, kingbaseOptionsAction: options => options.SetOracleCompatibilityMode())
            .Options;

        await using (var context = new ProbeDbContext(options))
        {
            using var transaction = context.Database.BeginTransaction();
            context.Entities.Add(new ProbeEntity { Id = 1, Name = "rolled-back", Version = 1 });
            Assert.Equal(1, context.SaveChanges());
            transaction.Rollback();
        }

        await using (var context = new ProbeDbContext(options))
        {
            Assert.False(await context.Entities.AnyAsync());
            await using var transaction = await context.Database.BeginTransactionAsync();
            context.Entities.Add(new ProbeEntity { Id = 2, Name = "committed", Version = 1 });
            Assert.Equal(1, await context.SaveChangesAsync());
            await transaction.CommitAsync();
        }

        await using (var context = new ProbeDbContext(options))
        {
            Assert.Equal("committed", await context.Entities.Select(row => row.Name).SingleAsync());
        }
    }

    private static async Task ResetTableAsync(KdbndpConnection connection)
    {
        await using var command = connection.CreateCommand();
        command.CommandText =
            """
            DROP TABLE IF EXISTS "efcore_provider_probe";
            CREATE TABLE "efcore_provider_probe" (
                "Id" integer NOT NULL,
                "Name" text NOT NULL,
                "Version" integer NOT NULL,
                CONSTRAINT "PK_efcore_provider_probe" PRIMARY KEY ("Id")
            );
            """;
        await command.ExecuteNonQueryAsync();
    }

    private static async Task<KdbndpConnection> OpenConnectionAsync(string connectionString)
    {
        Exception? lastException = null;

        for (var attempt = 1; attempt <= 3; attempt++)
        {
            var connection = new KdbndpConnection(connectionString);
            try
            {
                await connection.OpenAsync();
                return connection;
            }
            catch (Exception exception) when (attempt < 3)
            {
                lastException = exception;
                await connection.DisposeAsync();
                await Task.Delay(TimeSpan.FromSeconds(attempt));
            }
        }

        throw new InvalidOperationException("Unable to connect to the KingbaseES integration database after three attempts.", lastException);
    }

    private sealed class ProbeDbContext(DbContextOptions<ProbeDbContext> options) : DbContext(options)
    {
        public DbSet<ProbeEntity> Entities => Set<ProbeEntity>();
        public DbSet<IdentityProbeEntity> IdentityEntities => Set<IdentityProbeEntity>();

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            ConfigureEntity(modelBuilder.Entity<ProbeEntity>());
            modelBuilder.Entity<IdentityProbeEntity>(entity =>
            {
                entity.ToTable("efcore_identity_probe");
                entity.HasKey(row => row.Id);
                entity.Property(row => row.Id).ValueGeneratedOnAdd();
                entity.Property(row => row.Name).IsRequired();
            });
        }

        private static void ConfigureEntity(EntityTypeBuilder<ProbeEntity> entity)
        {
            entity.ToTable("efcore_provider_probe");
            entity.HasKey(row => row.Id);
            entity.Property(row => row.Id).ValueGeneratedNever();
            entity.Property(row => row.Name).IsRequired();
            entity.Property(row => row.Version).IsConcurrencyToken();
        }
    }

    private sealed class ProbeEntity
    {
        public int Id { get; set; }
        public string Name { get; set; } = string.Empty;
        public int Version { get; set; }
    }

    private sealed class IdentityProbeEntity
    {
        public int Id { get; set; }
        public string Name { get; set; } = string.Empty;
    }

    private sealed class EnsureCreatedDbContext(DbContextOptions<EnsureCreatedDbContext> options) : DbContext(options)
    {
        public DbSet<EnsureCreatedEntity> Entities => Set<EnsureCreatedEntity>();

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<EnsureCreatedEntity>(entity =>
            {
                entity.ToTable("efcore_ensure_created_probe");
                entity.HasKey(row => row.Id);
                entity.Property(row => row.Id).ValueGeneratedNever();
                entity.Property(row => row.Name).IsRequired();
            });
        }
    }

    private sealed class EnsureCreatedEntity
    {
        public int Id { get; set; }
        public string Name { get; set; } = string.Empty;
    }
}

[CollectionDefinition("Kingbase integration", DisableParallelization = true)]
public sealed class KingbaseIntegrationCollection;
