<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>AbpBookStore</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AbpBookStore.Application.Contracts\AbpBookStore.Application.Contracts.csproj" />
  </ItemGroup>

</Project>
