<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>AbpBookStore.EntityFrameworkCore</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Volo.Abp.EntityFrameworkCore" Version="10.6.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.9">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\src\Kingbase.EntityFrameworkCore\Kingbase.EntityFrameworkCore.csproj" />
    <ProjectReference Include="..\AbpBookStore.Domain\AbpBookStore.Domain.csproj" />
  </ItemGroup>

</Project>
