<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>AbpBookStore</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Volo.Abp.AspNetCore.Mvc" Version="10.6.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AbpBookStore.Application.Contracts\AbpBookStore.Application.Contracts.csproj" />
  </ItemGroup>

</Project>
